# Generated by Django 5.0.2 on 2024-04-27 03:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=2)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_transaccion', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=3)),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('id_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.cliente')),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 4, 27, 31441))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('monto', models.CharField(max_length=20)),
                ('id_cliente_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.cliente_producto')),
                ('tipo_transaccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.tipo_transaccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
