# Generated by Django 5.0.2 on 2024-04-27 03:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 3, 54, 694473))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 3, 54, 694473))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 3, 54, 694473))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 4, 26, 22, 3, 54, 694473))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('ident_number', models.CharField(blank=True, max_length=12)),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
